services:
    server:
        environment:
            - NODE_ENV=production
    client:
        container_name: client
        build: ./client
        restart: always
        depends_on:
            - server
        environment:
            - NODE_ENV=production
            - POSTGRES_HOST=database
        ports:
            - '5000:5000'
