services:
    database:
        container_name: database
        image: postgres
        restart: always
        env_file: ./.env
        volumes:
            - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    server:
        container_name: server
        build:
            context: ./server
        restart: always
        env_file: ./.env
        depends_on:
            - database
        ports:
            - '3000:3000'
