services:
    db:
        image: postgres
        env_file: ./.env
    server:
        build: ./server
        env_file: ./.env
        environment:
            - NODE_ENV=development
        depends_on:
            - db
        ports:
            - '3000:3000'
    client:
        build: ./client
        depends_on:
            - db
            - server
        ports:
            - '8080:8080'
